// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using NewfoundlandGenealogy.CensusData;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace NewfoundlandGenealogy.CensusData.MigrationService.Migrations
{
    [DbContext(typeof(CensusDbContext))]
    partial class CensusDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("NewfoundlandGenealogy.CensusData.Census", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("id");

                    b.Property<int>("CensusYear")
                        .HasColumnType("integer")
                        .HasColumnName("census_year");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("display_name");

                    b.Property<string>("NgbUrl")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("ngb_url");

                    b.Property<string>("Notes")
                        .HasMaxLength(2147483647)
                        .HasColumnType("text")
                        .HasColumnName("notes");

                    b.HasKey("Id")
                        .HasName("pk_censuses");

                    b.ToTable("censuses", (string)null);
                });

            modelBuilder.Entity("NewfoundlandGenealogy.CensusData.CensusDistrict", b =>
                {
                    b.Property<string>("CensusId")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("census_id");

                    b.Property<string>("Id")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("id");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("display_name");

                    b.Property<string>("NgbUrl")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("ngb_url");

                    b.Property<string>("Notes")
                        .HasMaxLength(2147483647)
                        .HasColumnType("text")
                        .HasColumnName("notes");

                    b.HasKey("CensusId", "Id")
                        .HasName("pk_census_districts");

                    b.ToTable("census_districts", (string)null);
                });

            modelBuilder.Entity("NewfoundlandGenealogy.CensusData.CensusTranscription", b =>
                {
                    b.Property<string>("CensusId")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("census_id");

                    b.Property<string>("DistrictId")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("district_id");

                    b.Property<string>("Id")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("id");

                    b.Property<string>("CensusDistrictCensusId")
                        .HasColumnType("character varying(100)")
                        .HasColumnName("census_district_census_id");

                    b.Property<string>("CensusDistrictId")
                        .HasColumnType("character varying(100)")
                        .HasColumnName("census_district_id");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("display_name");

                    b.Property<string>("MarkdownContent")
                        .IsRequired()
                        .HasMaxLength(2147483647)
                        .HasColumnType("text")
                        .HasColumnName("markdown_content");

                    b.Property<string>("NgbUrl")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("ngb_url");

                    b.Property<string>("Notes")
                        .HasMaxLength(2147483647)
                        .HasColumnType("text")
                        .HasColumnName("notes");

                    b.HasKey("CensusId", "DistrictId", "Id")
                        .HasName("pk_census_transcriptions");

                    b.HasIndex("CensusDistrictCensusId", "CensusDistrictId")
                        .HasDatabaseName("ix_census_transcriptions_census_district_census_id_census_dist");

                    b.ToTable("census_transcriptions", (string)null);
                });

            modelBuilder.Entity("NewfoundlandGenealogy.CensusData.CensusDistrict", b =>
                {
                    b.HasOne("NewfoundlandGenealogy.CensusData.Census", null)
                        .WithMany("Districts")
                        .HasForeignKey("CensusId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_census_districts_censuses_census_id");
                });

            modelBuilder.Entity("NewfoundlandGenealogy.CensusData.CensusTranscription", b =>
                {
                    b.HasOne("NewfoundlandGenealogy.CensusData.CensusDistrict", null)
                        .WithMany("Transcriptions")
                        .HasForeignKey("CensusDistrictCensusId", "CensusDistrictId")
                        .HasConstraintName("fk_census_transcriptions_census_districts_census_district_cens");
                });

            modelBuilder.Entity("NewfoundlandGenealogy.CensusData.Census", b =>
                {
                    b.Navigation("Districts");
                });

            modelBuilder.Entity("NewfoundlandGenealogy.CensusData.CensusDistrict", b =>
                {
                    b.Navigation("Transcriptions");
                });
#pragma warning restore 612, 618
        }
    }
}
